#############################################################################
# Makefile for building: ledpano
# Generated by qmake (2.01a) (Qt 4.7.3) on: Tue Jan 3 13:17:10 2017
# Project:  Ledpano.pro
# Template: app
# Command: /usr/local/Trolltech/QtEmbedded-4.7.3-arm/bin/qmake -spec /usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/qws/linux-arm-g++ CONFIG+=debug -o Makefile Ledpano.pro
#############################################################################

####### Compiler, tools and options

CC            = arm-linux-gcc
CXX           = arm-linux-g++
DEFINES       = -DQT_SQL_LIB -DQT_XML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/qws/linux-arm-g++ -I. -I/usr/local/Trolltech/QtEmbedded-4.7.3-arm/include/QtCore -I/usr/local/Trolltech/QtEmbedded-4.7.3-arm/include/QtNetwork -I/usr/local/Trolltech/QtEmbedded-4.7.3-arm/include/QtXml -I/usr/local/Trolltech/QtEmbedded-4.7.3-arm/include/QtSql -I/usr/local/Trolltech/QtEmbedded-4.7.3-arm/include -I.
LINK          = arm-linux-g++
LFLAGS        = -Wl,-rpath,/usr/local/Trolltech/QtEmbedded-4.7.3-arm/lib
LIBS          = $(SUBLIBS)  -L/usr/local/Trolltech/QtEmbedded-4.7.3-arm/lib -lQtSql -L/usr/local/Trolltech/QtEmbedded-4.7.3-arm/lib -lQtXml -lQtNetwork -lQtCore -lpthread 
AR            = arm-linux-ar cqs
RANLIB        = 
QMAKE         = /usr/local/Trolltech/QtEmbedded-4.7.3-arm/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = arm-linux-strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		ledpano.cpp \
		utility.cpp \
		i2c.cpp \
		hexdump.cpp \
		dbabstraction.cpp \
		logger.cpp 
OBJECTS       = main.o \
		ledpano.o \
		utility.o \
		i2c.o \
		hexdump.o \
		dbabstraction.o \
		logger.o
DIST          = /usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/common/g++.conf \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/common/unix.conf \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/common/linux.conf \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/common/qws.conf \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/qconfig.pri \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/debug.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/qt.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/moc.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/resources.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/uic.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/lex.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/include_source_dir.prf \
		Ledpano.pro
QMAKE_TARGET  = ledpano
DESTDIR       = 
TARGET        = ledpano

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Ledpano.pro  /usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/qws/linux-arm-g++/qmake.conf /usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/common/g++.conf \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/common/unix.conf \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/common/linux.conf \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/common/qws.conf \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/qconfig.pri \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/debug.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/qt.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/moc.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/resources.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/uic.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/lex.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/include_source_dir.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/lib/libQtSql.prl \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/lib/libQtCore.prl \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/lib/libQtXml.prl \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/lib/libQtNetwork.prl
	$(QMAKE) -spec /usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/qws/linux-arm-g++ CONFIG+=debug -o Makefile Ledpano.pro
/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/common/g++.conf:
/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/common/unix.conf:
/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/common/linux.conf:
/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/common/qws.conf:
/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/qconfig.pri:
/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/modules/qt_webkit_version.pri:
/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/qt_functions.prf:
/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/qt_config.prf:
/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/exclusive_builds.prf:
/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/default_pre.prf:
/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/debug.prf:
/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/default_post.prf:
/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/warn_on.prf:
/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/qt.prf:
/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/unix/thread.prf:
/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/moc.prf:
/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/resources.prf:
/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/uic.prf:
/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/yacc.prf:
/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/lex.prf:
/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/include_source_dir.prf:
/usr/local/Trolltech/QtEmbedded-4.7.3-arm/lib/libQtSql.prl:
/usr/local/Trolltech/QtEmbedded-4.7.3-arm/lib/libQtCore.prl:
/usr/local/Trolltech/QtEmbedded-4.7.3-arm/lib/libQtXml.prl:
/usr/local/Trolltech/QtEmbedded-4.7.3-arm/lib/libQtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/qws/linux-arm-g++ CONFIG+=debug -o Makefile Ledpano.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/ledpano1.0.0 || $(MKDIR) .tmp/ledpano1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/ledpano1.0.0/ && $(COPY_FILE) --parents ledpano.h utility.h i2c.h device.h hexdump.h dbabstraction.h logger.h main.h .tmp/ledpano1.0.0/ && $(COPY_FILE) --parents main.cpp ledpano.cpp utility.cpp i2c.cpp hexdump.cpp dbabstraction.cpp logger.cpp .tmp/ledpano1.0.0/ && (cd `dirname .tmp/ledpano1.0.0` && $(TAR) ledpano1.0.0.tar ledpano1.0.0 && $(COMPRESS) ledpano1.0.0.tar) && $(MOVE) `dirname .tmp/ledpano1.0.0`/ledpano1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/ledpano1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: main.cpp main.h \
		ledpano.h \
		utility.h \
		dbabstraction.h \
		device.h \
		i2c.h \
		logger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

ledpano.o: ledpano.cpp ledpano.h \
		utility.h \
		dbabstraction.h \
		device.h \
		i2c.h \
		logger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ledpano.o ledpano.cpp

utility.o: utility.cpp utility.h \
		logger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o utility.o utility.cpp

i2c.o: i2c.cpp hexdump.h \
		i2c.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o i2c.o i2c.cpp

hexdump.o: hexdump.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hexdump.o hexdump.cpp

dbabstraction.o: dbabstraction.cpp utility.h \
		dbabstraction.h \
		device.h \
		logger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dbabstraction.o dbabstraction.cpp

logger.o: logger.cpp logger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o logger.o logger.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

